package com.room.mokeys.maps.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.room.mokeys.maps.beans.BJCamera;
import com.room.mokeys.maps.beans.MusicBean;

import com.room.mokeys.maps.greendao.BJCameraDao;
import com.room.mokeys.maps.greendao.MusicBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bJCameraDaoConfig;
    private final DaoConfig musicBeanDaoConfig;

    private final BJCameraDao bJCameraDao;
    private final MusicBeanDao musicBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bJCameraDaoConfig = daoConfigMap.get(BJCameraDao.class).clone();
        bJCameraDaoConfig.initIdentityScope(type);

        musicBeanDaoConfig = daoConfigMap.get(MusicBeanDao.class).clone();
        musicBeanDaoConfig.initIdentityScope(type);

        bJCameraDao = new BJCameraDao(bJCameraDaoConfig, this);
        musicBeanDao = new MusicBeanDao(musicBeanDaoConfig, this);

        registerDao(BJCamera.class, bJCameraDao);
        registerDao(MusicBean.class, musicBeanDao);
    }
    
    public void clear() {
        bJCameraDaoConfig.clearIdentityScope();
        musicBeanDaoConfig.clearIdentityScope();
    }

    public BJCameraDao getBJCameraDao() {
        return bJCameraDao;
    }

    public MusicBeanDao getMusicBeanDao() {
        return musicBeanDao;
    }

}
